model:
  name: bert-base-uncased
  max_len: 128

model_alt_1:
  name: roberta-base
  max_len: 128

model_alt_2:
  name: microsoft/deberta-v3-base
  max_len: 128

training:
  batch_size_train: 16
  batch_size_valid: 16
  epochs: 3
  learning_rate: 2e-5

aspects:
  - gameplay
  - graphics
  - performance
  - story
  - controls
  - audio
  - price
  - multiplayer

paths:
  train: ./data/processed/absa_train.csv
  valid: ./data/valid.csv
  output_dir: ./outputs
